import Head from 'next/head'
import Link from 'next/link'

function Home() {
    return (
    <div>
        <Head>
            <title>Improveasy</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
    
            <header>
                <div>
                    <img className="w-[120px]" src="https://cdn-epabh.nitrocdn.com/FsnmazFPBRLJTCWWiBDcqyKZAxrlVTfk/assets/static/optimized/rev-921f197/wp-content/uploads/2022/01/Full_Logo_SVG.svg" alt="Improveasy Logo"/>
                </div>

                <nav>
                    <Link as="/" href="/landing/Home">
                        <a title="/">
                            <span className="text-[#ffffff]">Home</span>
                        </a>
                    </Link>
                    <Link as="/faq" href="/landing/FAQ">
                        <span>FAQ</span>
                    </Link>
                    <Link as="/mees" href="/landing/MEES">
                        <span>MEES</span>
                    </Link>
                    <Link as="/why-us" href="/landing/WhyUs">
                        <span>Why Us</span>
                    </Link>
                </nav>
            </header>

            <main>

            </main>

            <footer>
                    footer
            </footer>

        </div>


        </div>
    )
}

export default Home
