import Head from 'next/head'
import Link from 'next/link'

function Home() {
    return (
        <div>
        <Head>
            <title>Improveasy</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <div className="text-red-500">
               {/* Display all routes from landing */}
                    {/* layout is protected */}
                <header>
                    <div>
                        Logo
                    </div>

                    {/* <nav className="text-red-500">
                        <Link as="/" href="/landing/Home">
                            <a title="/">
                                <span>Home</span>
                            </a>
                        </Link>
                        <Link as="/faq" href="/landing/FAQ">
                            <span>FAQ</span>
                        </Link>
                        <Link as="/mees" href="/landing/MEES">
                            <span>MEES</span>
                        </Link>
                        <Link as="/why-us" href="/landing/WhyUs">
                            <span>Why Us</span>
                        </Link>
                    </nav> */}
                </header>

            </div>
        </div>
    )
}

export default Home
