import Head from 'next/head'
import Link from 'next/link'
import Footer from '../Footer'
import Header from '../Header'


function MainLayout({children, title}:any) {
    return (
        <>
            <Head>
                <title>{title} - Improveasy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta charSet="utf-8" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            </Head>
    

            <Header />

            <main>
                {children}
            </main>

            <Footer />

        </>
    )
}

export default MainLayout;
